grafana:
  persistence:
    enabled: true
    type: pvc
    storageClassName: standard
    accessModes:
      - ReadWriteOnce
    size: 20Gi
    finalizers:
      - kubernetes.io/pvc-protection
    resourcePolicy: keep
  securityContext:
    runAsUser: 472
    fsGroup: 472
  adminUser: admin
  adminPassword: admin
  service:
    type: ClusterIP
  readinessProbe:
    httpGet:
      path: /api/health
      port: 3000
    initialDelaySeconds: 120
    timeoutSeconds: 10
    periodSeconds: 15
    failureThreshold: 10

  livenessProbe:
    httpGet:
      path: /api/health
      port: 3000
    initialDelaySeconds: 180
    timeoutSeconds: 10
    periodSeconds: 30
    failureThreshold: 5
  replicaCount: 1
prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 32Gi
    retention: 30d
  readinessProbe:
    httpGet:
      path: /-/ready
      port: 9090
    initialDelaySeconds: 120
    timeoutSeconds: 10
    periodSeconds: 15
    failureThreshold: 10


alertmanager:
  enabled: false